# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb0cfe99058a98c7e19447b76dd80fd9ac7ae16006cd9dbabd676be93523b1069655a15aca9181e2201d837f1ace17b80b0ddbfd621b63536af7c7b3d54e205

test:
  secret_key_base: 1b2c9dfdad6ec7bdce6c790daab5727c6ba7b6180fc417fec5471e786146e78f7f9646badd2dbfc2c214a497be8456aedec2d596f14931578c977b941c54e707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
